### PR TITLE
Get it to install on my Ubuntu box.

### PR DESCRIPTION
**Pull request by harjitmoe**
Discord (installed via .deb) is in /usr/share/discord/resources so use that if Canary is not present.

### CODE REVIEW

**Comment by Inve1951** [comment]
not working?

**Comment by thomas-hori** [comment]
No, it's fine.  I'd just confused myself by mixing up multiple versions of the splice file.  The patched index.js should be fine with the current version.

**Comment by thomas-hori** [comment]
Have updated this PR for the current state of the master branch.

_(Some background for why I'm suddenly doing this: Forced manual client update on Linux effectively locked me out until I nuked `resources/app`, as it wasn't letting me in until it detected I'd updated, and while `resources/app.asar` was updated, `resources/app` was not for obvious reasons. So, I had to reïnstall BetterDiscord, and took the opportunity to try and install the current branch.)_

**Comment by Inve1951** [comment]
here's [Zerebos' fork](https://github.com/rauenzi/BetterDiscordApp) with a lot of fixes btw.

**Pull request closed without merging**
