### PR TITLE
added linux support

### PR DESCRIPTION
**Pull request by Francesco149**
This adds support for the alpha linux client that can be found here: https://www.reddit.com/r/discordapp/comments/4bu7lm/discord_linux_very_experimental_canary_release/

sorry about that mess with the installer's index.js, I believe my editor or git replaced all crlf's with lf's

how to install:

``` bash
cd
mkdir discord
cd discord

# Install discord in /opt/
wget https://storage.googleapis.com/discord-developer/test/discord-canary-0.0.1.tar.gz
tar -xzvf discord-canary-0.0.1.tar.gz
sudo cp -r DiscordCanary /opt/
sudo ln -s /opt/DiscordCanary/DiscordCanary /usr/bin/discord

# Install BetterDiscord
git clone https://github.com/Jiiks/BetterDiscordApp.git
mv BetterDiscordApp BetterDiscord
cp BetterDiscord/NodeInstaller/* .
cp BetterDiscord/splice .
npm install asar wrench
sudo ./install.sh
```

NOTE: for those who would like to try this before it gets merged or if it doesn't get merged, just replace Jiiks with Francesco149 in the git clone command

Note that discord might open at very weird positions (in my case the top left corner of my 2nd monitor).

EDIT:
Since I dislike font smoothing, I also made a basic css to disable most font smoothing (assumes you already disabled all hinting in your OS):

``` css
body, .tab-bar-item { 
    -webkit-font-smoothing: none; 
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
}
```

the webkit line is probably useless but I'll keep it just to be sure
not sure why the default font is smoothed even with hinting and smoothing disabled system-wide

NOTE:
Since 0.0.1 the discord window may be broken on start-up. If it is, close the window and terminate discord from the tray icon and re-start it. Keep doing this until it displays correctly. This is a Discord issue, not BetterDiscord's.

### CODE REVIEW

**Comment by Confuseh** [comment]
Installer was a mess for me, but end result works perfectly.
Problems that I had is that it wouldn't recursively copy the BetterDiscord directory (it would create the directory but wouldn't copy) and it would append index.js (one from /app) incorrectly (It would append lines 3, 7-8 to first three lines rather than in proper locations) - manually changing index.js and copying over BetterDiscord directory manually fixed it.

**Comment by Francesco149** [comment]
Are you sure you ran the installer script as root? That's some pretty mysterious behaviour, especially the wrong appending.

**Comment by Confuseh** [comment]
Yes, I am positive that I ran installer script as root.

**Comment by sarnex** [comment]
script worked perfectly for me

**Comment by Jiiks** [comment]
I'll test it at some point and merge if all goes well :+1:

**Comment by TheDoctorsLife** [comment]
This needs to be updated to version 0.0.3.

**Comment by sarnex** [comment]
I got it working on 0.0.3, but I'm sure it is not correct. All you need to do is paste this app.asar over your current one in DiscordCanary/resources, it should work.

https://idontevenlift.no-ip.org/app.asar

**Comment by DaFri-Nochiterov** [comment]
@sarnex, can you make new pull request with fixed code?

**Comment by sarnex** [comment]
yeah give me a few

**Comment by sarnex** [comment]
@DaFri-Nochiterov should be up now

**Comment by bb010g** [comment]
Needs a rebase.

**Comment by Francesco149** [comment]
this is wayyy outdated and linux support seems to have been added in the meantime, so I'm gonna close this

**Pull request closed without merging**
