### PR TITLE
Updated FFZ emotes =)

### PR DESCRIPTION
**Pull request by DeathStrikeV**

### CODE REVIEW

**Comment by bb010g** [comment]
Please rebase in the future instead of making a bunch of identical commits. They're fine to keep around during PR discussion, but they just clutter the log when merged without providing much value split up. It doesn't matter when you updated before merging to master, just what state FFZ emotes were at when they were updated in master.

**Comment by DeathStrikeV** [comment]
@bb010g Unfortunately the entire process on my end is semi-automated (now fully-automated), if you could suggest a clever way of rebasing without having to nitpick commits I'm open to suggestions =)

**Comment by bb010g** [comment]
You'd want to work on a branch (e.g. `ffz`), pull & fast-forward a clean `master` before starting. Run `git rebase master ffz` to pull your old commit to the head of master. Make your new update commit, but use `git commit --amend --reset-author` instead.

**Comment by DeathStrikeV** [comment]
@bb010g @Jiiks @pohky  It might actually be easier/better just to squash the pull request on github as I only ever do emote commits into this repo anyways. See step 3: https://help.github.com/articles/merging-a-pull-request/

**Pull request merged**
