### PR TITLE
Lots and lots of fixes and improvements

### PR DESCRIPTION
**Pull request by rauenzi**
I haven't changed any version numbers or anything, that's something I will leave up to you. There were changes in the local BetterDiscord.js for error checking and collection for plugins and themes, but the main.min.js file will still work without users being required to reinstall. As you can tell I did a ton of commits, lots of small ones because I wasn't testing with a local server but rather the remote github one. So if you want me to redo this PR with less commits just let me know.

Here's the list of everything that I've fixed, added, removed and improved. Feel free to test it through linking my repo in the config file. Let me know if you have any questions.
```md
Plugin/Theme Related
====================
- Fix onSwitch()
- Fix onMessage()
- Add try{} catch{} around plugin functions such as load, start, stop, observer, onSwitch, onMessage
- Add useful errors for unable to load or execute plugins
- Speed up loading plugins/themes
- Speed up executing the plugins' functions
- Allow themes to use non-alphanumeric names (they can have spaces and apostrophes now)
- Ignore folders and config files in the plugins/theme directories
- Prevent hanging when plugins are broken
- Redesign plugin/theme card DOM and css (make it more semantic and easier to style)
- Disable plugin settings button if plugin not enabled
- Smooth scroll to the plugin's settings when opened
- Allow "source" and "website" options in the META so they can be shown in plugin/theme cards


Emotes
======
- Fix not being able to click Twitch Emotes in menu
- Fix emote modifiers
- Fix emote tooltips overlapping the emote and flickering


Core
====
- Fix Minimal Mode
- Fix V2C errors when opening settings the first time
- Speed up the main observer
- Readd/Fix the "copy selector" for DevMode
- Update several CSS selectors for DOM changes
- Fix "selected" class disappearing on multiple clicks of a bd tab in settings
- Collect startup errors for plugins/themes including meta errors across local and the remotely linked file (BetterDiscord.js, Main.js)
- Create a modal that shows all the startup errors with a link to display the stack in console with a setting to disable the modal in core
- Fix/Update the alert modal, allow BdApi to use it
- Add toast alert functionality for Core and BdApi
- Add toasts for plugin/theme start/stop with corresponding setting to disable them in core
- Speed up 24 hour and colored text
- Apply/remove 24 hour and colored text immediately instead of waiting for the observer
- Attach to settings even when using other shortcuts by checking for the social links at the bottom


Code Cleanup
============
- Remove changelog stuff
- Remove PublicServers
- Remove old CustomCSS editor
- Remove BdWSocket and related items
- Remove broken BdApi items
- Basic ESLinting
```

### CODE REVIEW

**Comment by Orrielel** [comment]
Seems like Custom CSS isn't being applied on start up

**Comment by rauenzi** [comment]
Custom css now applies on start

**Comment by rauenzi** [comment]
@Jiiks I saw on BD2 you didn't like that other repo files were removed, I have readded them.

**Comment by rauenzi** [comment]
Closing this as it's essentially being maintained as an alternate and not meant to merge anymore.

**Pull request closed without merging**
