### PR TITLE
Fixed the 24-hour function for Compact

### PR DESCRIPTION
**Pull request by EraYaN**
And that without breaking the feature for Cozy.

### CODE REVIEW

**Comment by mkody** [comment]
Hmm... _Cozy_ still works, but that's not the case for _Compact_.

**Comment by EraYaN** [comment]
@mkody Have you tried this branch? It works locally here. For both Cozy and Compact.

**Comment by mkody** [comment]
Yes, I've merged your changes with the latest `main.js`.

**Comment by EraYaN** [comment]
Let me look at the branch again then.

**Comment by EraYaN** [comment]
I made a mistake in thinking that .text() returned everything. Well I switched it to .html() and a replace based strategy. The regex is much simpler and cleaner now. This also leaves the Discord HTML intact they put around Compact-style time stamps. It should also be able to deal with any format that includes am/pm/AM/PM. 

For now only languages using am/pm/AM/PM would be supported. Others could be added, not sure how javascript deals with stuff like Asian scripts.

**Comment by EraYaN** [comment]
I rebased this pull request on latest master. Could you have a look at it again, so it makes v2.0?

**Comment by Lazersmoke** [comment]
This may or may not fix #519

**Comment by EraYaN** [comment]
This should fix it if the class is correct. And since it uses a little bit more liberal regex now, it should just work outright.

**Pull request closed without merging**
