### PR TITLE
Update emotefilter.json

### PR DESCRIPTION
**Pull request by Darentei**
Intrusive emotes using common names, words or phrases suck. I added a few to the blacklist.

### CODE REVIEW

**Comment by Zerthox** [comment]
May I add those to my PR? Then Jiiks only has to merge one.

**Comment by Novabella** [comment]
Yamato Shinobu Jeanne Ayyy AAAAA AYYY THICC SUCC CUCC Hiro Nono Oooh RUDE should also be added to the blacklist.

**Comment by Novabella** [comment]
Doggo is an emote, and SHOULD NOT be an emote. To be honest, any single words shouldn't be an emote. Should at least have "GASM" at the end, or some random letters before it or something.

**Comment by Novabella** [comment]
Pfft Pffft Imperfect

**Comment by Jiiks** [comment]
Conflict merged: https://github.com/Jiiks/BetterDiscordApp/commit/031c64271ac4bcabdc25cd5080753c3814a037ee

**Pull request closed without merging**
