### PR TITLE
Fix Twitch emotes failing to load

### PR DESCRIPTION
**Pull request by gmt2001**
Fixed Twitch emotes failing to load and causing a JS error due to twitchemotes.com enforcing https only

### CODE REVIEW

**Comment by cosmicsalad** [comment]
Emotes temp fix:

Replace the BetterDiscord.js file in:
"%localappdata%\Discord\app-0.0.283\resources\node_modules\BetterDiscord\Lib"
With the following: 
https://github.com/Jiiks/BetterDiscordApp/blob/master/lib/BetterDiscordT.js

Also delete all .json files in %appdata%\BetterDiscord

Then restart discord.

**Comment by cosmicsalad** [comment]
That's what this already does: https://github.com/Jiiks/BetterDiscordApp/blob/master/lib/BetterDiscordT.js

**Comment by gmt2001** [comment]
That file makes it pull from a manually updated file in this repo. My fix pulls from the live list on twitchemotes.com which is constantly updated

**Comment by Jiiks** [comment]
This was applied with 0.2.6. Thanks :)

**Pull request closed without merging**
